---
title: "teacher_2d"
output: html_document
date: "2022-08-12"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(here)
library(tidyverse)
library(lme4)
library(lmerTest)
library(brms)
library(ggthemes)
library(tidyboot)

options(contrasts = c(unordered = "contr.sum", ordered = "contr.poly"))

theme_set(theme_few(base_size = 15))
```

```{r}
d <- read.csv(here('data/teacher_2d/pilot1/cleaned_long.csv'))

d.seq <- d %>% filter(sequential == "sequential")
d.nonseq <- d %>% filter(sequential == "non_sequential")
```

# Non-sequential conditions

In the full knowledge case, do participants consider what students know or don't know? 

```{r}
nonseq.mod <- d.nonseq %>% 
  lmer(
  dist ~ 1 + teacher_knowledge * known + (1 + teacher_knowledge * known | subject_id) + (1 + teacher_knowledge * known | concept_size), 
  data = .
)

summary(nonseq.mod)
```

- Do people produce more corners based on the condition? 
- 


```{r}
d.nonseq.corners <- d.nonseq %>% 
  group_by(teacher_knowledge, concept_size, known) %>% 
  tidyboot_mean(
    corner, na.rm = T
  )

d.nonseq.distances <- d.nonseq %>% 
  group_by(teacher_knowledge, concept_size, known) %>% 
  tidyboot_mean(
    dist, na.rm = T
  )

d.nonseq.corners
d.nonseq.distances
```
```{r}
ggplot(d.nonseq.distances, aes(x = teacher_knowledge, y = empirical_stat, color = known)) + 
    geom_point(size = 2, position = position_dodge(width = 0.1)) + 
    geom_errorbar(aes(ymin = ci_lower, ymax = ci_upper), size = 1, width = 0, position = position_dodge(width = 0.15)) + 
    theme(aspect.ratio = 1.2) + 
    scale_color_discrete(labels = c("known boundary", "unknown boundary")) +
    labs(x = "teacher knowledge", y = "distance to boundary", title = "different 1d concept sizes", col = "student knowledge") +
     facet_wrap(~concept_size)
```
Look at corners

```{r}
ggplot(d.nonseq.corners, aes(x = teacher_knowledge, y = empirical_stat, color = known)) + 
    geom_point(size = 2, position = position_dodge(width = 0.1)) + 
    geom_errorbar(aes(ymin = ci_lower, ymax = ci_upper), size = 1, width = 0, position = position_dodge(width = 0.15)) + 
    theme(aspect.ratio = 1.2) + 
    scale_color_discrete(labels = c("known boundary", "unknown boundary")) +
    labs(x = "teacher knowledge", y = "proportion corners", title = "proportion corners", col = "student knowledge") +
     facet_wrap(~concept_size)
```


What if we break it out by true hypothesis? 

```{r}
d.nonseq.corners <- d.nonseq %>% 
  group_by(teacher_knowledge, known_concept_size, unknown_concept_size, known) %>% 
  tidyboot_mean(
    corner, na.rm = T
  )

d.nonseq.distances <- d.nonseq %>% 
  group_by(teacher_knowledge, known_concept_size, unknown_concept_size, known) %>% 
  tidyboot_mean(
    dist, na.rm = T
  )
```

```{r}
known_concept_size.labs <- c("known: 2", "known: 4", "known: 6")
names(known_concept_size.labs) <- c(2, 4, 6)

unknown_concept_size.labs <- c("unknown: 2", "unknown: 4", "unknown: 6")
names(unknown_concept_size.labs) <- c(2, 4, 6)

ggplot(d.nonseq.distances, aes(x = teacher_knowledge, y = empirical_stat, color = known)) + 
    geom_point(size = 1.5, position = position_dodge(width = 0.15)) + 
    geom_errorbar(aes(ymin = ci_lower, ymax = ci_upper), size = 1, width = 0, position = position_dodge(width = 0.15)) + 
    theme(aspect.ratio = 1) + 
    scale_color_discrete(labels = c("known boundary", "unknown boundary")) +
    labs(x = "teacher knowledge", y = "distance to boundary", title = "distance to boundary for each concept dimension", col = "student knowledge") +
     facet_grid(known_concept_size ~ unknown_concept_size, labeller = labeller(known_concept_size = known_concept_size.labs, unknown_concept_size = unknown_concept_size.labs)) + 
  theme_few(base_size = 14)
```


# Sequential conditions? 




